# -*- coding: utf-8 -*-
"""mini_shop_management_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwRovKcnHVPUTwDmFinfvgbJQTdMYjUe

#general store
"""

products = {
  "p01": {"product_name" : "pen",
           "price" : 30 ,                #cell no 1 ( DICTIONARY )
           "quantity" : 10},
    "p02":
     { "product_name" : "pencil",
           "price" : 10 ,
           "quantity" : 20
     },
    "p03":
     {"product_name" : "book",
           "price" : 300 ,
           "quantity" : 20}
}

product_id = input("Enter Product ID: ")
product_name = input("Enter Product Name: ")
price = float(input("Enter Price: "))
quantity = int(input("Enter Quantity: "))  # cell no 2 ( ADD MORE INFO )
products[product_id] = {
    "product_name": product_name,
    "price": price,
    "quantity": quantity
}

print(products)

for product_id, product in products.items():
  print(product_id)

for product, product in products.items():
  print(product)

for product_id, product in products.items():
    print("ID:", product_id)           # cell no 3  ( VIEW)


    print("Name:", product_name)
    print("Price:", product["price"])
    print("Quantity:", product["quantity"])
    print()

def search_product():

    product_id = input("Enter Product ID: ")

    if product_id in products:
        print("Product Found!")
        print("Product ID:", product_id)                                    # stock available or not
        print("Product Name:", products[product_id]["product_name"])
        print("Price:", products[product_id]["price"])
        print("Quantity:", products[product_id]["quantity"])

    else:
        print("Product Not Found!")

search_product()

def sale_product():

    product_id = input("Enter Product ID: ")

    if product_id not in products:
        print("Product not found!")
        return

    sale_quantity = int(input("Enter quantity to sell: "))        # sell/ calculate price

    available_quantity = products[product_id]["quantity"]

    if sale_quantity > available_quantity:
        print("Insufficient stock!")
        print("Available stock:", available_quantity)

    else:
        price = products[product_id]["price"]
        total_amount = price * sale_quantity

        products[product_id]["quantity"] -= sale_quantity
        sales.append({
    "product_id": product_id,
    "quantity": sale_quantity,
    "total": total_amount
})

        print("Sale successful!")
        print("Total amount:", total_amount)
        print("Remaining stock:", products[product_id]["quantity"])

sale_product()

print(sales)

def low_stock():
    low_products = [
        (product["product_name"], product["quantity"])
        for product in products.values()
        if product["quantity"] < 5
    ]

    print("\nLOW STOCK PRODUCTS")
                                                  #low stock
    if not low_products:
        print("No low-stock products.")
        return

    for name, quantity in low_products:
        print(name, "-", quantity, "remaining")

low_stock()

def sales_summary():
    total_products_sold = 0
    total_sales = 0                              # sales summary

    for sale in sales:
        total_products_sold += sale["quantity"]
        total_sales += sale["total"]

    print("Total Products Sold:", total_products_sold)
    print("Total Sales Amount: Rs.", total_sales)

sales_summary()

def price_list():
    product_prices = {
        product_id: product["price"]
        for product_id, product in products.items()          # price list
    }

    print("\n========== PRODUCT PRICES ==========")

    for product_id, price in product_prices.items():
        print(product_id, "- Rs.", price)

price_list()

def sort_products_by_price():
    product_list = list(products.values())   # sorted by price

    sorted_products = sorted(
        product_list,
        key=lambda x: x["price"]
    )

    print("\n========== PRODUCTS SORTED BY PRICE ==========")

    for product in sorted_products:
        print(product["product_name"], "- Rs.", product["price"])

sort_products_by_price()

def count_items(items, index=0):
    if index == len(items):
        return 0

    return 1 + count_items(items, index + 1)

count_items(products)

def add_stock(product_id, quantity):
    product = products.get(product_id)

    if product is None:
        return False

    product["quantity"] += quantity
    return True

def add_stock_menu():
    product_id = input("Enter product ID: ").strip()

    product = products.get(product_id)

    if product is None:
        print("Product not found!")
        return

    quantity = int(input("Enter quantity to add: "))

    if quantity <= 0:
        print("Quantity must be greater than 0.")
        return

    if add_stock(product_id, quantity):
        print("Stock updated successfully!")
        print(f"Product: {product['product_name']}")
        print(f"New quantity: {product['quantity']}")

add_stock_menu()

sales = []

def main_menu():
    while True:
        print("\n========== MINI SHOP MANAGEMENT SYSTEM ==========")
        print("1. Add Product")
        print("2. View Products")
        print("3. Search Product")
        print("4. Sell Product")
        print("5. Low Stock Products")
        print("6. Sales Summary")
        print("7. Price List")
        print("8. Sort Products by Price")
        print("9. Count Products")
        print("10. Add Stock")
        print("11. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            product_id = input("Enter Product ID: ")
            product_name = input("Enter Product Name: ")
            price = float(input("Enter Price: "))
            quantity = int(input("Enter Quantity: "))

            products[product_id] = {
                "product_name": product_name,
                "price": price,
                "quantity": quantity
            }

            print("Product added successfully!")

        elif choice == "2":
            for product_id, product in products.items():
                print("\nID:", product_id)
                print("Name:", product["product_name"])
                print("Price:", product["price"])
                print("Quantity:", product["quantity"])

        elif choice == "3":
            search_product()

        elif choice == "4":
            sale_product()

        elif choice == "5":
            low_stock()

        elif choice == "6":
            sales_summary()

        elif choice == "7":
            price_list()

        elif choice == "8":
            sort_products_by_price()

        elif choice == "9":
            print("Total Products:", count_items(products))

        elif choice == "10":
            add_stock_menu()

        elif choice == "11":
            print("Thank you for using Mini Shop Management System!")
            break

        else:
            print("Invalid choice! Please try again.")

main_menu()